#!/bin/bash
# SPDX-License-Identifier: Apache-2.0
# Build script for the clamp_swiglu_fwd_bf16 TPC kernel:
#   1. kernel_src.c  -> kernel.o      (tpc-clang, gaudi2 target)
#   2. kernel.o      -> kernel_binary.h (embedded ELF bytes)
#   3. entry_points.cpp + kernel_binary.h -> libclamp_swiglu_kernels.so (GC glue)
# The torch extension (ext_src.cpp) is built separately by loader.py
# (torch.utils.cpp_extension) because it must link against the venv's torch.
set -euo pipefail
cd "$(dirname "$0")"

TPCINC=${TPCINC:-/usr/lib/habanatools/include}

echo "[1/4] tpc-clang: kernel_src.c -> kernel.o"
tpc-clang kernel_src.c -c -x c++ -march=gaudi2 -O2 -o kernel.o


embed() {
    python3 - "$1" "$2" <<'EOF'
import sys, pathlib
src, dst = sys.argv[1], sys.argv[2]
b = pathlib.Path(src).read_bytes()
name = 'clamp_swiglu_fwd_bf16'
with open(dst, "w") as f:
    f.write("// generated by build.sh\n")
    f.write(f"const unsigned char {name}[{len(b)}] = {{\n")
    for i in range(0, len(b), 16):
        f.write(",".join("0x%02x" % x for x in b[i:i+16]) + ",\n")
    f.write("};\n")
    f.write(f"const unsigned int {name}_len = {len(b)};\n")
EOF
}

echo "[3/4] embedding ELF -> kernel_binary.h"
embed kernel.o kernel_binary.h
grep -q 'clamp_swiglu_fwd_bf16_len' kernel_binary.h || { echo "embedding failed"; exit 1; }

echo "[4/4] g++: glue library -> libclamp_swiglu_kernels.so"
g++ -std=c++17 -O2 -fPIC -shared \
    -I"$TPCINC" \
    entry_points.cpp -o libclamp_swiglu_kernels.so

echo "OK: kernel.o, kernel_binary.h, libclamp_swiglu_kernels.so"
