// SPDX-License-Identifier: Apache-2.0
// Glue code for clamp_swiglu_fwd_bf16 — exposes the TPC kernel ELF to the
// Gaudi graph compiler via the two mandatory entry points
// (GetKernelGuids / InstantiateTpcKernel). Build with build.sh.

#include <cstdint>
#include <cstring>
#include <string>

#include "tpc_kernel_lib_interface.h"
#include "kernel_binary.h"   // bf16 kernel ELF (generated by build.sh)

using namespace tpc_lib_api;

// must match ext_src.cpp
struct ClampSwigluNodeParams
{
    float limit;
};

static const char* kGuid    = "clamp_swiglu_fwd_bf16";

extern "C"
{

GlueCodeReturn GetKernelGuids(DeviceId deviceId, uint32_t* kernelCount, GuidInfo* guids)
{
    if (deviceId != DEVICE_ID_GAUDI2)
        return GLUE_NODE_NOT_FOUND;
    if (kernelCount == nullptr)
        return GLUE_FAILED;
    if (*kernelCount == 0)
    {
        *kernelCount = 1;
        return GLUE_SUCCESS;
    }
    if (guids == nullptr)
        return GLUE_FAILED;

    memset(&guids[0], 0, sizeof(GuidInfo));
    strncpy(guids[0].name, kGuid, MAX_NODE_NAME - 1);
    return GLUE_SUCCESS;
}

GlueCodeReturn InstantiateTpcKernel(const HabanaKernelParams* params, HabanaKernelInstantiation* instance)
{    if (params == nullptr || instance == nullptr)
        return GLUE_FAILED;

    const GuidInfo& guid = params->guid;
    if (strncmp(guid.name, kGuid, MAX_NODE_NAME) != 0)
        return GLUE_NODE_NOT_FOUND;

    if (params->inputTensorNr != 1 || params->outputTensorNr != 1)
        return GLUE_INCOMPATIBLE_INPUT_COUNT;

    const Tensor& in  = params->inputTensors[0];
    const Tensor& out = params->outputTensors[0];

    if (in.geometry.dataType != DATA_BF16 || out.geometry.dataType != DATA_BF16)
        return GLUE_INCOMPATIBLE_DATA_TYPE;
    // dims <= 2 ONLY: the kernel addresses rows via coordinates (c[0], c[1])
    // against a 2-D descriptor. A rank>2 tensor was previously accepted here
    // with T = product(dims[1:]) — the kernel then walked c[1] beyond the
    // descriptor's dim1 size (dims 2+ never got coordinates), silently
    // producing garbage (verified: [16,6,4096] direct call ~95% wrong values).
    // Higher ranks must be flattened by the CALLER (the vllm_gaudi dispatch
    // reshapes to 2-D); reject here so misuse fails loudly at compile time.
    if (in.geometry.dims < 1 || in.geometry.dims > 2 || out.geometry.dims != in.geometry.dims)
        return GLUE_UNSUPPORTED_LAYER_CONFIGURATION;

    // FCD = dim0 (fastest changing). 2I on input, I on output; T = product of
    // the remaining dims.
    const uint64_t twoI = in.geometry.maxSizes[0];
    if ((twoI & 1ull) != 0 || twoI < 2)
        return GLUE_INCOMPATIBLE_INPUT_SIZE;
    const uint64_t I = twoI >> 1;

    uint64_t T = 1;
    for (uint32_t d = 1; d < in.geometry.dims; ++d)
        T *= in.geometry.maxSizes[d];
    if (T == 0)
        return GLUE_INCOMPATIBLE_INPUT_SIZE;

    if (out.geometry.maxSizes[0] != I)
        return GLUE_INCOMPATIBLE_OUTPUT_SIZE;
    uint64_t Tout = 1;
    for (uint32_t d = 1; d < out.geometry.dims; ++d)
        Tout *= out.geometry.maxSizes[d];
    if (Tout != T)
        return GLUE_INCOMPATIBLE_OUTPUT_SIZE;

    // scalar params: limit (fp32)
    if (params->nodeParams.nodeParams == nullptr || params->nodeParams.nodeParamsSize < sizeof(ClampSwigluNodeParams))
        return GLUE_KERNEL_INVALID_SCALAR_ARGUMENT;
    const ClampSwigluNodeParams* np = reinterpret_cast<const ClampSwigluNodeParams*>(params->nodeParams.nodeParams);

    // ---- index space: dim0 = I in ELEMENTS (not vectors!) and dim1 = tokens.
    // (Element-units convention, simulator-verified by the glm52 glue on this
    // box: the kernel steps c[0] by 128 element units itself and GC partitions
    // dim0 at vector granularity using the load width in the ELF. Declaring
    // vector counts under-runs every member owning >128 elements.)
    instance->indexSpaceRank      = 2;
    instance->indexSpaceGeometry[0] = I;
    instance->indexSpaceGeometry[1] = T;
    instance->indexSpaceGeometry[2] = 1;
    instance->indexSpaceGeometry[3] = 1;
    instance->indexSpaceGeometry[4] = 1;

    // ---- access patterns (static: outlives this call) ----
    static TensorAccessPattern inAP;
    static TensorAccessPattern outAP;
    memset(&inAP, 0, sizeof(inAP));
    memset(&outAP, 0, sizeof(outAP));

    // Input: each invocation reads the gate vector AND the matching up
    // vector (+I along FCD) — an offset not expressible as a per-dim affine
    // map, so declare full-tensor access (allRequired) and let GC be safe.
    inAP.allRequired = 1;
    inAP.mapping[0].indexSpaceDim = 0;
    inAP.mapping[0].a             = 1.f; // 1 element per index unit
    inAP.mapping[0].start_b       = 0.f;
    inAP.mapping[0].end_b         = 0.f;
    inAP.mapping[0].allRequired   = true;
    inAP.mapping[1].indexSpaceDim = 1;
    inAP.mapping[1].a             = 1.f;
    inAP.mapping[1].start_b       = 0.f;
    inAP.mapping[1].end_b         = 0.f;
    inAP.mapping[1].allRequired   = true;

    // Output: pure affine map — fully declared.
    outAP.mapping[0].indexSpaceDim = 0;
    outAP.mapping[0].a             = 1.f;
    outAP.mapping[0].start_b       = 0.f;
    outAP.mapping[0].end_b         = 0.f;
    outAP.mapping[0].allRequired   = true;
    outAP.mapping[1].indexSpaceDim = 1;
    outAP.mapping[1].a             = 1.f;
    outAP.mapping[1].start_b       = 0.f;
    outAP.mapping[1].end_b         = 0.f;
    outAP.mapping[1].allRequired   = true;

    instance->inputTensorAccessPattern  = &inAP;
    instance->outputTensorAccessPattern = &outAP;

    instance->auxiliaryTensorNr = 0; // GC pre-sets 16; we require none
    instance->preferredSplitDim = 0;
    instance->kernelUsesLock    = 0;

    // ---- kernel ELF ----
    const uint32_t elfBytes = clamp_swiglu_fwd_bf16_len;
    if (instance->kernel.kernelElf == nullptr || instance->kernel.elfSize < elfBytes)
    {
        instance->kernel.elfSize = elfBytes;
        return GLUE_INSUFFICIENT_ELF_BUFFER;
    }
    memcpy(instance->kernel.kernelElf, clamp_swiglu_fwd_bf16, elfBytes);
    instance->kernel.elfSize  = elfBytes;
    instance->kernel.paramsNr = 1;
    float                     lim = np->limit;
    instance->kernel.scalarParams[0] = *reinterpret_cast<uint32_t*>(&lim);

    return GLUE_SUCCESS;
}

// Mandatory in SynapseAI 1.24: the kernel DB rejects libraries without this
// entry point ("No Entry point GetShapeInference" -> guid not found).
GlueCodeReturn GetShapeInference(DeviceId                 deviceId,
                                 const ShapeInferenceParams* inputParams,
                                 ShapeInferenceOutput*      outputData)
{
    if (deviceId != DEVICE_ID_GAUDI2)
        return GLUE_NODE_NOT_FOUND;
    if (inputParams == nullptr || outputData == nullptr)
        return GLUE_SIF_NULL_PTR;
    if (inputParams->inputTensorsNr == 1 && inputParams->outputTensorsNr == 1)
    {
        const TensorShapeInfo* in = inputParams->inputTensors[0];
        if (in == nullptr)
            return GLUE_FAILED;
        if (in->geometry.dims < 1 || in->geometry.dims > 2)
            return GLUE_UNSUPPORTED_LAYER_CONFIGURATION; // kernel is 2-D only
        const uint64_t twoI = in->geometry.maxSizes[0];
        if ((twoI & 1ull) != 0 || twoI < 2)
            return GLUE_INCOMPATIBLE_INPUT_SIZE;
        TensorShapeInfo* out = outputData->outputTensors[0];
        if (out == nullptr)
            return GLUE_FAILED;
        out->geometry             = in->geometry;
        out->geometry.maxSizes[0] = twoI >> 1;
        out->geometry.dataType    = DATA_BF16;
        out->hostAddress          = nullptr;
        return GLUE_SUCCESS;
    }
    if (inputParams->inputTensorsNr == 2 && inputParams->outputTensorsNr == 1)
    {
        const TensorShapeInfo* h8 = inputParams->inputTensors[0];
        if (h8 == nullptr || h8->geometry.dims != 2)
            return GLUE_FAILED;
        const uint64_t twoI = h8->geometry.maxSizes[0];
        if ((twoI & 1ull) != 0 || twoI < 2)
            return GLUE_INCOMPATIBLE_INPUT_SIZE;
        TensorShapeInfo* out = outputData->outputTensors[0];
        if (out == nullptr)
            return GLUE_FAILED;
        out->geometry             = h8->geometry;
        out->geometry.maxSizes[0] = twoI >> 1;
        out->geometry.dataType    = DATA_BF16;
        out->hostAddress          = nullptr;
        return GLUE_SUCCESS;
    }
    return GLUE_INCOMPATIBLE_INPUT_COUNT;
}

// Optional but reported by the kernel DB when missing; declare layout-agnostic
// (mirrors the working glm52 glue on this box: fill ONLY set [0], 'x' = agnostic).
GlueCodeReturn GetSupportedDataLayouts(const HabanaKernelParams* params,
                                        NodeDataLayouts*          supportedLayouts,
                                        uint32_t*                 layoutCount)
{
    if (params == nullptr || layoutCount == nullptr)
        return GLUE_FAILED;
    if (strncmp(params->guid.name, kGuid, MAX_NODE_NAME) != 0)
        return GLUE_NODE_NOT_FOUND;
    if (supportedLayouts == nullptr || *layoutCount == 0)
    {
        *layoutCount = 1;
        return GLUE_SUCCESS;
    }
    if (supportedLayouts->inputs && supportedLayouts->inputTensorNr > 0)
        memset(supportedLayouts->inputs[0].layout, 'x', MAX_TENSOR_DIM);
    if (supportedLayouts->outputs && supportedLayouts->outputTensorNr > 0)
        memset(supportedLayouts->outputs[0].layout, 'x', MAX_TENSOR_DIM);
    *layoutCount = 1;
    return GLUE_SUCCESS;
}

uint64_t GetLibVersion()
{
    return 1;
}

} // extern "C"
